module(
    name = "com_google_guava",
    version = "999.0.0-HEAD-jre-SNAPSHOT",
)

bazel_dep(name = "rules_java", version = "9.0.3")
bazel_dep(name = "rules_jvm_external", version = "6.7")

java_toolchains = use_extension("@rules_java//java:extensions.bzl", "toolchains")
use_repo(java_toolchains, "remotejdk25_linux")

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")

maven.install(
    artifacts = [
        "com.google.guava:failureaccess:1.0.3",
        "com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava",
        "org.jspecify:jspecify:1.0.0",
        "com.google.errorprone:error_prone_annotations:2.47.0",
        "com.google.j2objc:j2objc-annotations:3.1",
        "com.google.code.findbugs:jsr305:3.0.2",
        "junit:junit:4.13.2",
        "com.google.truth:truth:1.4.5",
    ],
)

use_repo(maven, "maven")
